name: Release Workflow
on: [push]

jobs:

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    steps:
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v2.0.0
        with:
          helmfile-version: v0.157.0
          helm-version: v3.13.1
          install-kubectl: false
