name: Release Workflow
on: [push]

jobs:
  setup-helmfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
        with:
          helmfile-version: v0.157.0  # Fixed typo in version
          helm-version: v3.13.1
          install-kubectl: false
          helm-s3-plugin-version: v0.16.2  # Explicit version
          install-helm-plugins: true
